### ISSUE TITLE
1.7.0 ver. is broken,cant auto fish

### ISSUE THREAD

**Issue by sam0324sam** [xiaoye97/CoreKeeperAutoFish#7]
1.7.0 ver. is broken,cant auto fish

**Comment by xiaoye97** [comment]
After testing, it can run normally. Please check the log to see if there are other conditions that cause mod to fail.

**Comment by sam0324sam** [comment]
IDK why it can't work.
In 1.6.0 is work fine.
I back to 1.6.0 is work fine too.
I only install auto door and auto fish

```[Message: Preloader] BepInEx 6.0.0-be.664 - CoreKeeper
[Message: Preloader] Built from commit 0b23557c1355913983f3540797fa22c43a02247d
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.37f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [AutoDoor 1.0.0]
[Info   :Il2CppInterop] Registered mono type AutoDoor.MonoWoodDoorThing in il2cpp domain
[Info   :  AutoDoor] Plugin AutoDoor is loaded!
[Info   :   BepInEx] Loading [CoreKeeperAutoFish 1.7.0]
[Error  :   BepInEx] Error occurred loading plugins: System.IO.FileNotFoundException: Could not load file or assembly 'CoreLib, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'. 蝟餌絞?曆??唳?摰?瑼???
File name: 'CoreLib, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.IsDefined(Type attributeType, Boolean inherit)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
   at System.IO.FileNotFoundException.ToString()
   at System.Exception.ToString()
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 421
   at BepInEx.Bootstrap.BaseChainloader`1.Execute() in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 317
[Message:   BepInEx] Chainloader startup complete
[Message:     Unity] Skipping automatic Manager prelaunch because this should be done manually in the Loading scene.
[Warning:     Unity] The referenced script on this Behaviour (Game Object 'SysInfo') is missing!
[Message:     Unity] Core count is 24
[Message:     Unity] Job worker count is 4
[Message:     Unity] Steam API initialized branch=
[Message:     Unity] Using save prefix
[Message:     Unity] CloudSyncDown
[Message:     Unity] Version: 0.5.1.2-4398
[Info   :  AutoDoor] Memory manager init rn: False
[Info   :  AutoDoor] prefab list: 369
[Info   :  AutoDoor] Door is WoodDoor and is type GameObject
[Info   :  AutoDoor] Door registered successfully as a WoodDoor object
[Info   :  AutoDoor] 1
[Info   :  AutoDoor] 2
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Info   :  AutoDoor] This will work! i hope well its getting setup at least
[Warning:     Unity] FontJapanese: Already defined glyph #179 嚗?
[Warning:     Unity] FontJapanese: Already defined glyph #278 ??
[Warning:     Unity] FontJapanese: Already defined glyph #179 嚗?
[Warning:     Unity] FontJapanese: Already defined glyph #278 ??
[Warning:     Unity] FontJapanese: Already defined glyph #179 嚗?
[Warning:     Unity] FontJapanese: Already defined glyph #278 ??
[Warning:     Unity] The referenced script on this Behaviour (Game Object '<null>') is missing!
[Warning:     Unity] The referenced script on this Behaviour (Game Object 'SysInfo') is missing!
[Warning:     Unity] The referenced script on this Behaviour (Game Object 'SysInfo') is missing!
[Message:     Unity] No iCUE server detected
[Message:     Unity] Steam stats received
[Message:     Unity] Steam stats received
[Message:     Unity] Couldn't find backing drive, assumes there is space
[Message:     Unity] Client connecting to session WAE55uGM6L6svS4twPL1acCbzCV9
[Message:     Unity] Steam auth: Current
[Message:     Unity] Found responsive internet server
[Message:     Unity] Connecting to server 憭折???
[Message:     Unity] Trying to connect to userid:90169019511950342
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p_ice.cpp (734) : Assertion Failed: We gathered candidate type 0x4, but 0x202 is allowed
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp (1873) : Assertion Failed: SteamnetworkingSockets service thread waited 613ms for lock!  This directly adds to network latency!  It could be a bug, but it's usually caused by general performance problem such as thread starvation or a debug output handler taking too long.
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p_ice.cpp (734) : Assertion Failed: We gathered candidate type 0x4, but 0x202 is allowed
[Message:     Unity] Client connected to userid:90169019511950342
[Message:     Unity] Sending authentication message with result OK
[Message:     Unity] Got OK authentication response
[Message:     Unity] Client connected
[Message:     Unity] Connected to server 憭折???(80ce58d374ff08d25d73f259bc954a7d)
[Message:     Unity] PugDatabase initialized 1729 prefabs
[Message:     Unity] number prefabs 1564
[Message:     Unity] Try trigger achievement MaxedOutFishing
[Message:     Unity] Steam stats stored
[Message:     Unity] Steam stats stored
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Warning:     Unity] Trying to place in same spot or the same entity too quick, gotta wait for server.
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Message:     Unity] detecting inconsistent inventory; slow network?
[Warning:     Unity] Player(Clone): Can't abort ongoing state change! Fishing -> Walk. Are you trying to change the state in OnExitState?
```

**Comment by Krormar** [comment]
After game update nether 1.6 or 1.7 work

this is error massage I get when trying to run 1.7

[Error  :   BepInEx] Error occurred loading plugins: System.IO.FileNotFoundException: Could not load file or assembly 'CoreLib, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'. Nie mo┼╝na odnale┼║─ç okre┼Ťlonego pliku.
File name: 'CoreLib, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.IsDefined(Type attributeType, Boolean inherit)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
   at System.IO.FileNotFoundException.ToString()
   at System.Exception.ToString()
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 421
   at BepInEx.Bootstrap.BaseChainloader`1.Execute() in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 317

**Comment by Krormar** [comment]
After game update auto-fishing mod don't work for me. Nethier 1.6 or 1.7

This is error I get for 1.7 version

[Nowy dokument tekstowy (4).txt](https://github.com/xiaoye97/CoreKeeperAutoFish/files/10685936/Nowy.dokument.tekstowy.4.txt)

**Comment by sam0324sam** [comment]
my too

**Comment by xiaoye97** [comment]
Valentine's Day update caused mod error. I need some time to check.

**Comment by xiaoye97** [comment]
Now fix
